
branches:
  only:
  - master

dist: trusty
language: minimal

jobs:
  include:
    - stage: release
      script:
      - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
      - make build DEBUG=false
      - make tag_latest DEBUG=false
      - make release DEBUG=false
      - curl -s -X POST https://hooks.microbadger.com/images/${TRAVIS_REPO_SLUG}/evcn6a67rZc_UychWDShxAocMnE=
      - curl -s -X POST https://hooks.microbadger.com/images/${TRAVIS_REPO_SLUG}-min/CpU1SAWEalplATynvPpglQR7a04="
